version: '3.1'
services:
  bookmedik:
    container_name: bookmedik-app
    image: lainwireless/bookmedik:v3
    restart: always
    environment:
      USUARIO_BOOKMEDIK: admin
      CONTRA_BOOKMEDIK: admin
      DATABASE_HOST: bd_mariadb
      NOMBRE_DB: bookmedik
    ports:
      - 8082:80
    depends_on:
      - db
      - php
    volumes:
      - phpdocs:/usr/share/nginx/html/
  db:
    container_name: bd_mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
  php:
    container_name: book_php
    image: lainwireless/php-fpm-mysql:v1
    restart: always
    environment:
      USUARIO_BOOKMEDIK: admin
      CONTRA_BOOKMEDIK: admin
      DATABASE_HOST: bd_mariadb
      NOMBRE_DB: bookmedik
    volumes:
      - phpdocs:/usr/share/nginx/html/

volumes:
    mariadb_data:
    phpdocs: